name: woocommerce-sse-server
services:
  - type: app
    data:
      projectName: woocommerce-sse-server
      serviceName: woocommerce-sse-server
      source:
        type: github
        owner: your-username
        repo: woocommerce-mcp-server
        branch: main
      build:
        type: buildpacks
        buildCommand: npm install && npm run build
        startCommand: npm start
      domains:
        - host: others-woomcp.g5n7ma.easypanel.host
          https: true
      env:
        - name: SERVER_MODE
          value: http
        - name: PORT
          value: "80"
        - name: NODE_ENV
          value: production
        - name: EASYPANEL_DOMAIN
          value: https://others-woomcp.g5n7ma.easypanel.host
        - name: DEBUG
          value: "true"
        - name: WORDPRESS_SITE_URL
          value: https://your-wordpress-site.com
        - name: WOOCOMMERCE_CONSUMER_KEY
          value: ck_your_consumer_key_here
        - name: WOOCOMMERCE_CONSUMER_SECRET
          value: cs_your_consumer_secret_here
        - name: WORDPRESS_USERNAME
          value: your_wordpress_username
        - name: WORDPRESS_PASSWORD
          value: your_wordpress_app_password
      mounts: []
      ports:
        - published: 80
          target: 80
      replicas: 1
      cpus: 1.0
      memory: 1024
      healthCheck:
        path: /health
        port: 80
        initialDelaySeconds: 90
        periodSeconds: 30
        timeoutSeconds: 15
        failureThreshold: 5
      readinessProbe:
        path: /ready
        port: 80
        initialDelaySeconds: 45
        periodSeconds: 15
        timeoutSeconds: 10
      livenessProbe:
        path: /health
        port: 80
        initialDelaySeconds: 120
        periodSeconds: 45
        timeoutSeconds: 20
        failureThreshold: 3 